tableSchema:
  patientleave:
    record_id: INTEGER
    patient_id: INTEGER
    date_time: STRING
    in_out: STRING
    reason: STRING
    sign_by: STRING

  patient:
    name: STRING
    age: INTEGER
    patient_id: INTEGER

pipeline:
  fileImport:
    run: true
    options:
      project: sookplatformspikes_file_import
      runner: DirectRunner
      dataSet: spike_dlp_oesc_mysql_migration
      inputFilePath: /Users/akhilghatiki/oesc/spikes/dlp-rdb-bq-import/src/main/resources/oesc_on_prem_patient.tsv
      fileDeLimiter: \t
      tempLocation: gs://spike_oesc/dlp-file-import
      DLPConfigBucket: spike_oesc
      DLPConfigObject: spike_dpl_template_oesc.json
